#+title: biblio-openlibrary | An OpenLibrary backend for biblio.el

~biblio-openlibrary~ provides a backend for [[https://github.com/cpitclaudel/biblio.el][biblio.el]], which allows you to easily search
and retrieve bibliographic entries by ISBN using [[https://openlibrary.org/][OpenLibrary]]'s [[https://openlibrary.org/dev/docs/api/read][Read API]].

* Motivation
[[https://github.com/cpitclaudel/biblio.el][biblio.el]] is a great package that allows for the retrieval of bibliographic
entries from many sources. However, it does not support queries based on ISBN.
This package aims to provide a solution for this.

** Scope
 [[https://openlibrary.org/][OpenLibrary]]'s [[https://openlibrary.org/dev/docs/api/read][Read API]] allows for queries based on a multitude of identifiers,
 not only ISBN. /Currently/, *this package only allows, and expects, queries based on
 an ISBN identifier*, mainly due to ~biblio.el~ already providing functionality for
 the other, most common, use cases.
 
* Installation
Using ~package.el~ and [[https://github.com/slotThe/vc-use-package][vc-use-package]]:
#+begin_src emacs-lisp 
(use-package biblio-openlibrary
  :vc (:fetcher github :repo fabcontigiani/biblio-openlibrary)
  :after biblio)
#+end_src

Using ~package-vc~, execute:
#+begin_src emacs-lisp
(package-vc-install "https://github.com/fabcontigiani/biblio-openlibrary")
#+end_src

Manually, after cloning the repository: 
#+begin_src emacs-lisp 
(use-package biblio-openlibrary
  :load-path "/path/to/repo"
  :after biblio)
#+end_src

* Usage
Perform a ~M-x biblio-lookup~ and select the new option =OpenLibrary=, or do an =M-x
openlibrary-lookup=, then provide an ISBN identifier to query.
